-
    name: General
    options:
        -
            doc: This help message
            option: help
            short: h
            command: help
        -
            doc: The version of isearcher
            option: version
            short: v
            command: version
        -
            doc: The folder that the lucene index locate, if not set, will use .index folder in current working directory
            option: index_dest
            short: d
            args: true
            command: set
-
    name: Indexing
    options:
        -
            doc: Create the lucene index, you can set the folder to index
            option: create
            short: c
            command: create
        -
            doc: Update the lucene index, isearcher will store the modify time of every indexed document, and if the document is changed(modify time is changed, or the file don't have any modify time stored), will update the index of this document in the lucene index
            option: update
            short: u
            command: update
-
    name: Index Folder
    options:
        -
            doc: The folder that needs to be indexed
            option: index_folder
            short: i
            args: true
            command: set
-
    name: Index Include and Exclude
    options:
        -
            doc: The pattern that should exclude(using the file system globbing pattern)
            option: exclude
            short: e
            args: true
            command: set
        -
            doc: The pattern that should include(using the file system globbing pattern)
            option: file_name
            short: n
            args: true
            command: set
-
    name: Get Configuration
    options:
        -
            doc: Get the configuration
            option: get
            short: g
            args: true
            command: get
-
    name: Search
    options:
        -
            doc: Do the search
            option: search
            short: s
            args: true
            command: search
